apiVersion: apps/v1                       
kind: Deployment                       
metadata:                         
  labels:                           
    app: demospringalien  
  name: demospringalien
spec:                         
  replicas: 2                 
  selector:                           
    matchLabels:               
      app: demospringalien 
  template:                         
    metadata:                   
      labels:                 
        app: demospringalien  
    spec:        
      containers:  
      - image:  nexus.docker.internal:5000/repository/demo/service-a:latest
      name: demospringalien
